### 1. Criar um usuário (Registrar)
POST http://localhost:9090/auth/register
Content-Type: application/json

{
  "nome": "Aluno Teste",
  "email": "aluno@uece.br",
  "senha": "123"
}

### 2. Testar Login
POST http://localhost:9090/auth/login
Content-Type: application/json

{
  "email": "aluno@uece.br",
  "senha": "123"
}